// NEXT
import type { Metadata } from "next";
// PACKAGES
import { ReactQueryProvider } from "@/context/ReactQueryContext";
// UTILS
import { roboto, poppins } from "@/utils/fonts";
import { cn } from "@/utils/helpers";
// STYLES
import '@/styles/global.css';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body 
        className={cn(
          "min-h-screen bg-background font-roboto antialiased",
          roboto.variable,
          poppins.variable
        
        )}
      >
        <ReactQueryProvider>
          <main>
            {children}
          </main>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
