import type { Metadata } from "next";
// UTILS
import { roboto, poppins } from "@/utils/fonts";
// STYLES
import '@/styles/global.css';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${poppins.variable}`}>{children}</body>
    </html>
  );
}
